# -*- coding: utf-8 -*-
"""
Список блоков по сложностям.

id      — имя файла текстуры в static/textures (без .png)
ru / en — названия (по ним проверяется ответ игрока)

Лёгкая  — самые известные блоки.
Средняя — лёгкая + блоки посложнее.
Профи   — строится АВТОМАТИЧЕСКИ из всех скачанных текстур,
          так что в игру попадают вообще все блоки.
"""

EASY_BLOCKS = [
    {"id": "grass_block_side", "ru": "Дёрн", "en": "Grass Block"},
    {"id": "dirt", "ru": "Земля", "en": "Dirt"},
    {"id": "stone", "ru": "Камень", "en": "Stone"},
    {"id": "cobblestone", "ru": "Булыжник", "en": "Cobblestone"},
    {"id": "oak_planks", "ru": "Дубовые доски", "en": "Oak Planks"},
    {"id": "oak_log", "ru": "Дубовое бревно", "en": "Oak Log"},
    {"id": "oak_leaves", "ru": "Дубовая листва", "en": "Oak Leaves"},
    {"id": "sand", "ru": "Песок", "en": "Sand"},
    {"id": "gravel", "ru": "Гравий", "en": "Gravel"},
    {"id": "clay", "ru": "Глина", "en": "Clay"},
    {"id": "snow", "ru": "Снежный блок", "en": "Snow Block"},
    {"id": "ice", "ru": "Лёд", "en": "Ice"},
    {"id": "glass", "ru": "Стекло", "en": "Glass"},
    {"id": "bricks", "ru": "Кирпичный блок", "en": "Bricks"},
    {"id": "bookshelf", "ru": "Книжная полка", "en": "Bookshelf"},
    {"id": "crafting_table_top", "ru": "Верстак", "en": "Crafting Table"},
    {"id": "furnace_front", "ru": "Печка", "en": "Furnace"},
    {"id": "tnt_side", "ru": "ТНТ", "en": "TNT"},
    {"id": "diamond_block", "ru": "Алмазный блок", "en": "Block of Diamond"},
    {"id": "gold_block", "ru": "Золотой блок", "en": "Block of Gold"},
    {"id": "iron_block", "ru": "Железный блок", "en": "Block of Iron"},
    {"id": "emerald_block", "ru": "Изумрудный блок", "en": "Block of Emerald"},
    {"id": "coal_block", "ru": "Угольный блок", "en": "Block of Coal"},
    {"id": "coal_ore", "ru": "Угольная руда", "en": "Coal Ore"},
    {"id": "iron_ore", "ru": "Железная руда", "en": "Iron Ore"},
    {"id": "gold_ore", "ru": "Золотая руда", "en": "Gold Ore"},
    {"id": "diamond_ore", "ru": "Алмазная руда", "en": "Diamond Ore"},
    {"id": "obsidian", "ru": "Обсидиан", "en": "Obsidian"},
    {"id": "bedrock", "ru": "Бедрок", "en": "Bedrock"},
    {"id": "netherrack", "ru": "Адский камень", "en": "Netherrack"},
    {"id": "glowstone", "ru": "Светящийся камень", "en": "Glowstone"},
    {"id": "carved_pumpkin", "ru": "Резная тыква", "en": "Carved Pumpkin"},
    {"id": "melon_side", "ru": "Арбуз", "en": "Melon"},
    {"id": "hay_block_side", "ru": "Сноп сена", "en": "Hay Bale"},
    {"id": "sponge", "ru": "Губка", "en": "Sponge"},
    {"id": "slime_block", "ru": "Блок слизи", "en": "Slime Block"},
]

MEDIUM_BLOCKS = [
    {"id": "sandstone", "ru": "Песчаник", "en": "Sandstone"},
    {"id": "red_sand", "ru": "Красный песок", "en": "Red Sand"},
    {"id": "soul_sand", "ru": "Песок душ", "en": "Soul Sand"},
    {"id": "soul_soil", "ru": "Почва душ", "en": "Soul Soil"},
    {"id": "mycelium_top", "ru": "Мицелий", "en": "Mycelium"},
    {"id": "end_stone", "ru": "Камень Края", "en": "End Stone"},
    {"id": "quartz_block_side", "ru": "Кварцевый блок", "en": "Quartz Block"},
    {"id": "purpur_block", "ru": "Пурпурный блок", "en": "Purpur Block"},
    {"id": "prismarine", "ru": "Призмарин", "en": "Prismarine"},
    {"id": "sea_lantern", "ru": "Морской фонарь", "en": "Sea Lantern"},
    {"id": "magma", "ru": "Магмовый блок", "en": "Magma Block"},
    {"id": "dried_kelp_side", "ru": "Блок сушёных водорослей", "en": "Dried Kelp Block"},
    {"id": "nether_wart_block", "ru": "Блок адского нароста", "en": "Nether Wart Block"},
    {"id": "warped_wart_block", "ru": "Блок искажённого нароста", "en": "Warped Wart Block"},
    {"id": "bone_block_side", "ru": "Костяной блок", "en": "Bone Block"},
    {"id": "ancient_debris_side", "ru": "Древние обломки", "en": "Ancient Debris"},
    {"id": "crying_obsidian", "ru": "Плачущий обсидиан", "en": "Crying Obsidian"},
    {"id": "gilded_blackstone", "ru": "Позолоченный чернокамень", "en": "Gilded Blackstone"},
    {"id": "blackstone", "ru": "Чернокамень", "en": "Blackstone"},
    {"id": "basalt_side", "ru": "Базальт", "en": "Basalt"},
    {"id": "deepslate", "ru": "Глубинный сланец", "en": "Deepslate"},
    {"id": "moss_block", "ru": "Блок мха", "en": "Moss Block"},
    {"id": "mossy_cobblestone", "ru": "Мшистый булыжник", "en": "Mossy Cobblestone"},
    {"id": "stone_bricks", "ru": "Каменные кирпичи", "en": "Stone Bricks"},
    {"id": "terracotta", "ru": "Терракота", "en": "Terracotta"},
    {"id": "white_wool", "ru": "Белая шерсть", "en": "White Wool"},
    {"id": "lapis_block", "ru": "Лазуритовый блок", "en": "Block of Lapis"},
    {"id": "redstone_block", "ru": "Блок красного камня", "en": "Block of Redstone"},
    {"id": "emerald_ore", "ru": "Изумрудная руда", "en": "Emerald Ore"},
    {"id": "lapis_ore", "ru": "Лазуритовая руда", "en": "Lapis Ore"},
    {"id": "redstone_ore", "ru": "Красная руда", "en": "Redstone Ore"},
    {"id": "nether_gold_ore", "ru": "Золотая руда Незера", "en": "Nether Gold Ore"},
    {"id": "nether_quartz_ore", "ru": "Кварцевая руда", "en": "Nether Quartz Ore"},
    {"id": "amethyst_block", "ru": "Аметистовый блок", "en": "Block of Amethyst"},
    {"id": "copper_block", "ru": "Медный блок", "en": "Block of Copper"},
    {"id": "raw_iron_block", "ru": "Блок сырого железа", "en": "Block of Raw Iron"},
    {"id": "raw_gold_block", "ru": "Блок сырого золота", "en": "Block of Raw Gold"},
    {"id": "netherite_block", "ru": "Блок незерита", "en": "Block of Netherite"},
    {"id": "nether_bricks", "ru": "Адские кирпичи", "en": "Nether Bricks"},
    {"id": "brown_mushroom_block", "ru": "Коричневый гриб", "en": "Brown Mushroom Block"},
    {"id": "jack_o_lantern", "ru": "Светящаяся тыква", "en": "Jack o'Lantern"},
    {"id": "note_block", "ru": "Музыкальный блок", "en": "Note Block"},
    {"id": "jukebox_side", "ru": "Проигрыватель", "en": "Jukebox"},
    {"id": "target_side", "ru": "Мишень", "en": "Target"},
    {"id": "lodestone_side", "ru": "Магнетит", "en": "Lodestone"},
    {"id": "shroomlight", "ru": "Грибосвет", "en": "Shroomlight"},
    {"id": "dragon_egg", "ru": "Драконье яйцо", "en": "Dragon Egg"},
]